### ISSUE TITLE
Consistency in access_token names

### ISSUE THREAD

**Issue by jateeter** [GreenButtonAlliance/OpenESPI-GreenButton-API-Documentation#15]
There is an inconsistency in the way we speak about the (6) various access_tokens. The GreenButtonAuthorization.docx defines these and we should stick with these names in all cases.

access_token: allocated by datacustodian for individual account authorizations
refresh_token: allocated at the time of authoriztion and used to renew an access_token
datacustodian_access_token: access token used by trusted administrative accounts
client_access_token: used by thirdparty applications to access bulk or multiple authorization subscriptions
upload_access_token: used by MeterDataManagement (backend) systems to upload/import data into a datacustodian 
registration_access_token: reserved for future use in dynamic registration patterns

**Comment by jateeter** [comment]
One place that is inconsistent is Appendix B (Section 4) of the GreenButtonAuthorization.docx file.

**Comment by MartyBurns** [comment]
I am interpreting what you say as the the abbreviation column in appendix B vs. the named access-tokens in section 1.2.2?

That said, I have added the access token definition tables from the API spreadsheet to appendix B. The names match with section 1.2.2.

This will be in the next version I post to the http://osgug.ucaiug.org/sgsystems/OpenADE/Shared%20Documents/Testing%20and%20Certification/GreenButtonTestPlan/referenceMaterial/GreenButtonAuthorization.docx.
