### ISSUE TITLE
ElectricPowerUsageSummary for a specific Subscription/UsagePoint combination returns multiple usage points

### ISSUE THREAD

**Issue by rashmichitrakar** [GreenButtonAlliance/OpenESPI-GreenButton-API-Documentation#24]
I am using the GreenButtonData API sandbox and testing the ElectricPowerUsageSummary for user Alan (subscription ID = 5) with the access token for Alan (Bearer c59f88ed-26fb-4650-b07e-d5a031bfeb63).

When calling the ElectricPowerUsageSummary using the following API call, I see all UsagePoints 1 - 12 returned for Subscription 5. 

Here is the API call:
https://services.greenbuttondata.org:443/DataCustodian/espi/1_1/resource/Subscription/5/UsagePoint/1/ElectricPowerUsageSummary?published-max=All&published-min=All&updated-max=All&updated-min=All&max-results=All&start-index=1&depth=All

Shouldn't this data be limited only to UsagePoint 1 given Subscription 5 has only 1 UsagePoint? Even if it had multiple usage points, the fact that I have asked for only UsagePoint 1 should be honored?

**Comment by MartyBurns** [comment]
I can confirm the problem. It seems that a get on a collection bypasses the filter of resources in the response to those that belong to Usageapoints in the subscription,

**Comment by rashmichitrakar** [comment]
Thanks for confirming Marty. For now, I can use the "batch" API called by passing in a subscription and that seems to return the ElectricPowerUsageSummary for the usage points for that subscription alone.
