### ISSUE TITLE
API sandbox not returning any data

### ISSUE THREAD

**Issue by rashmichitrakar** [GreenButtonAlliance/OpenESPI-GreenButton-API-Documentation#25]
None of the API calls in the sandbox seem to be working since the past few days. I am testing using the Data Custodian token and here is a sample output from one of the calls. I've also tried the batch API with subscription ID and I get the same response. Can someone please take a look and provide a resolution?We are building a sample app based on this and are presently blocked.

Request URL
https://services.greenbuttondata.org:443/DataCustodian/espi/1_1/resource/ApplicationInformation?published-max=All&published-min=All&updated-max=All&updated-min=All&max-results=All&start-index=1&depth=All

Response Body
no content
Response Code
0
Response Headers
{}

Thanks,
Rashmi

**Comment by dfcoffin** [comment]
Rasmi,

Thank you for alerting us to this issue.  We are investigating the source of the problem and expect to have it corrected shortly.

Thanks,
Don

**Comment by rashmichitrakar** [comment]
Thank you!  Much appreciated.

**Comment by dfcoffin** [comment]
Rashmi,

Please retry the API transaction and let me know the results.  It should be working now with the data_custodian_access_token.

**Comment by rashmichitrakar** [comment]
Works like a charm! Thank you for the speedy fix!
