### ISSUE TITLE
Authentication error for Data Custodian Access token

### ISSUE THREAD

**Issue by rovp** [GreenButtonAlliance/OpenESPI-GreenButton-API-Documentation#29]
After giving Data Custodian Access token it giving an authentication error
<oauth>
  <error_description>No Authorization Found</error_description>
  <error>access_denied</error>
</oauth>

for GET /espi/1_1/resource/Authorization

**Comment by dfcoffin** [comment]
#rovp The source of the issue has been identified and resolved.  Please retry your request.

**Comment by rovp** [comment]
It was working after your comment . But now api is showing the same issue

**Comment by dfcoffin** [comment]
#rovp I've reset the application, it is working again.

**Comment by tedWexus** [comment]
I get the following error for every request I try to make:
```
<oauth>
  <error_description>Access Not Authorized</error_description>
  <error>access_denied</error>
</oauth>
```

**Comment by dfcoffin** [comment]
@tedWexus  

Thank you for reporting the issue.

The application has been restarted, which temporarily solves the issue causing the error message you encountered.  We are actively attempting to determine a permanent solution to the problem and thank you for your patience.
