### ISSUE TITLE
Sample Access token not working

### ISSUE THREAD

**Issue by Donklord** [GreenButtonAlliance/OpenESPI-GreenButton-API-Documentation#32]
Hello, I am attempting developing an API connection using the green button [this](http://greenbuttonalliance.github.io/OpenESPI-GreenButton-API-Documentation/API/) API documentation.  However, all of the API tokens dont work when trying them out in this application.

**Comment by dfcoffin** [comment]
@Donklord 

I have resolved the issue.  The target Data Custodian application had to be restarted.  Sorry for the inconvenience

**Comment by dfcoffin** [comment]
@Donklord 

Please e-mail me (dcoffin@greenbuttonalliance.org) and I'll provide instructions so you can resolve the issue in the future.

**Comment by Donklord** [comment]
That works now!  Thank you for the quick response.
